### ISSUE TITLE
Add a gentler introduction to Bluetooth in the document

### ISSUE THREAD

**Issue by hdevalence** [Co-Epi/CEN#24]
Branching out from https://github.com/Co-Epi/CEN/pull/23#issuecomment-608053359

The current Bluetooth section assumes knowledge of Bluetooth (I just copied it from the Google Doc), so it doesn't define a lot of the terms it uses.

**Comment by hdevalence** [comment]
cc @zssz

**Comment by zssz** [comment]
I'm working on this currently.
