### ISSUE TITLE
Consider terminology change from "Contact Event Numbers"

### ISSUE THREAD

**Issue by hdevalence** [Co-Epi/CEN#37]
As discussed on the cross-organizational Zoom call, we should try to standardize terminology between all the different contact tracing protocols.

One point of discussion was the term "Contact Event Number".  Some points of discussion:

- the name should not have "ID" in the name, because this suggests that there's a strong identity, which is not the case;
- the name should have something that indicates that it's a short-lived value;
- "ephemeral" is less clear than "temporary" for non-native English speakers.

A preliminary alternative is "Temporary Contact Number" (TCN)

**Comment by zssz** [comment]
I like "Temporary Tag" (TT) also.

**Comment by hdevalence** [comment]
@zssz Would you be happy with "TCN"/"TCK"?

**Comment by hdevalence** [comment]
Making this change isn't particularly difficult -- it just requires careful search-and-replace -- but it does touch basically every part of the repository, so it will cause any outstanding changes to have conflicts.

For this reason I would like to: 1) definitively decide on new terms, if we decide to change terms at all 2) wait for all in-flight work to land 3) make the change then.

**Comment by hdevalence** [comment]
Doing this now.
