### ISSUE TITLE
what is the process to get type reserved as part of memo field

### ISSUE THREAD

**Issue by rajagottumukkala** [Co-Epi/CEN#83]
We are working on using TCN for our implementation and we are interested in reserving for type like CoEpi and CovidWatch. Can someone help me with the process?

**Comment by scottleibrand** [comment]
You can make a pull request directly against https://github.com/TCNCoalition/TCN/blob/main/README.md (by clicking the pencil icon to edit).

**Comment by rajagottumukkala** [comment]
Thank you
